# Generated by Django 5.1.4 on 2024-12-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_education_status_vacancy_applied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='user',
            new_name='applicant',
        ),
    ]
